#undef FIELD_BONUS
#undef FIELD_LINKED
#undef FIELD_LOCKED

#undef SPEC_RECIPE
#undef SPEC_PRODUCTION
#undef SPEC_FINISH
#undef SPEC_ITEM

#undef THEORY_NEEDS_ITEM
#undef THEORY_INCOMPATIBLE
#undef THEORY_CANNOT_PROGRESS
#undef THEORY_SUCCESS

#undef POINTS_PER_TIER