version: "1"
rules:                          # Array of rules
  - base: auto_pull             # Required. Target branch
    upstream: dev               # Required. Must be in the same fork network.
    mergeMethod: hardreset      # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: auto_pull             # Required. Target branch
    upstream: NebulaSS13:dev    # Required. Must be in the same fork network.
    mergeMethod: merge          # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.