version: "2"
rules:                      # Array of rules
  - base: dev               # Required. Target branch
    upstream: NebulaSS13:dev    # Required. Must be in the same fork network.
    mergeMethod: merge      # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees:              # Optional
      - biscuitWizard
    reviewers:              # Optional
      - biscuitWizard
    conflictReviewers:      # Optional
      - biscuitWizard
label: ":arrow_heading_down: pull"  # Optional