
SAVED_VAR(/obj/effect/overmap, unknown_id)
SAVED_VAR(/obj/effect/overmap, scannable)
SAVED_VAR(/obj/effect/overmap, halted)
SAVED_VAR(/obj/effect/overmap, can_move)
SAVED_VAR(/obj/effect/overmap, sensor_visibility)
SAVED_VAR(/obj/effect/overmap, vessel_mass)
SAVED_VAR(/obj/effect/overmap, max_speed)
SAVED_VAR(/obj/effect/overmap, min_speed)
SAVED_VAR(/obj/effect/overmap, speed)
SAVED_VAR(/obj/effect/overmap, position)
SAVED_VAR(/obj/effect/overmap, overmap_id)

SAVED_VAR(/obj/effect/overmap/visitable, generic_waypoints)
SAVED_VAR(/obj/effect/overmap/visitable, restricted_waypoints)
SAVED_VAR(/obj/effect/overmap/visitable, docking_codes)
SAVED_VAR(/obj/effect/overmap/visitable, start_x)
SAVED_VAR(/obj/effect/overmap/visitable, start_y)
SAVED_VAR(/obj/effect/overmap/visitable, sector_flags)
SAVED_VAR(/obj/effect/overmap/visitable, hide_from_reports)
SAVED_VAR(/obj/effect/overmap/visitable, has_distress_beacon)
SAVED_VAR(/obj/effect/overmap/visitable, free_landing)
SAVED_VAR(/obj/effect/overmap/visitable, rent_amount)
SAVED_VAR(/obj/effect/overmap/visitable, paid_rent)
SAVED_VAR(/obj/effect/overmap/visitable, rent_period)
SAVED_VAR(/obj/effect/overmap/visitable, last_due)

SAVED_VAR(/obj/effect/shuttle_landmark, base_area)
SAVED_VAR(/obj/effect/shuttle_landmark, base_turf)
SAVED_VAR(/obj/effect/shuttle_landmark, shuttle_restricted)
SAVED_VAR(/obj/effect/shuttle_landmark/ship, shuttle_name)
SAVED_VAR(/obj/effect/shuttle_landmark/ship, visitors)
SAVED_VAR(/obj/effect/shuttle_landmark/visiting_shuttle,core_landmark)

SAVED_VAR(/datum/shuttle/autodock/overmap, range)
SAVED_VAR(/datum/shuttle/autodock/overmap, fuel_consumption)
SAVED_VAR(/datum/shuttle/autodock/overmap, fuel_ports)
SAVED_VAR(/datum/shuttle/autodock/overmap, skill_needed)
SAVED_VAR(/datum/shuttle/autodock/overmap, operator_skill)