/obj/item/modular_computer/examine(mob/user)
	. = ..()
	var/datum/extension/assembly/assembly = get_extension(src, /datum/extension/assembly)
	var/obj/item/stock_parts/computer/mem_slot/mem_slot = assembly.get_component(PART_MEM)
	if(mem_slot && mem_slot.stored_memory)
		to_chat(user, "\The [mem_slot.stored_memory] is inserted into it.")
	assembly.examine(user)
