
SAVED_VAR(/mob/living/exosuit, emp_damage)
SAVED_VAR(/mob/living/exosuit, saved_access)
SAVED_VAR(/mob/living/exosuit, sync_access)
SAVED_VAR(/mob/living/exosuit, pilots)
SAVED_VAR(/mob/living/exosuit, arms)
SAVED_VAR(/mob/living/exosuit, legs)
SAVED_VAR(/mob/living/exosuit, head)
SAVED_VAR(/mob/living/exosuit, body)
SAVED_VAR(/mob/living/exosuit, selected_system)
SAVED_VAR(/mob/living/exosuit, selected_hardpoint)
SAVED_VAR(/mob/living/exosuit, hardpoints)
SAVED_VAR(/mob/living/exosuit, hardpoints_locked)
SAVED_VAR(/mob/living/exosuit, maintenance_protocols)
SAVED_VAR(/mob/living/exosuit, hatch_closed)
SAVED_VAR(/mob/living/exosuit, hatch_locked)
SAVED_VAR(/mob/living/exosuit, use_air)

SAVED_VAR(/obj/item/mech_component, on_mech_icon)
SAVED_VAR(/obj/item/mech_component, exosuit_desc_string)
SAVED_VAR(/obj/item/mech_component, total_damage)
SAVED_VAR(/obj/item/mech_component, brute_damage)
SAVED_VAR(/obj/item/mech_component, burn_damage)
SAVED_VAR(/obj/item/mech_component, damage_state)
SAVED_VAR(/obj/item/mech_component, has_hardpoints)
SAVED_VAR(/obj/item/mech_component, power_use)

SAVED_VAR(/obj/item/mech_component/manipulators, melee_damage)
SAVED_VAR(/obj/item/mech_component/manipulators, action_delay)
SAVED_VAR(/obj/item/mech_component/manipulators, motivator)

SAVED_VAR(/obj/item/mech_component/chassis, mech_health)
SAVED_VAR(/obj/item/mech_component/chassis, cell)
SAVED_VAR(/obj/item/mech_component/chassis, diagnostics)
SAVED_VAR(/obj/item/mech_component/chassis, air_supply)
SAVED_VAR(/obj/item/mech_component/chassis, cockpit)
SAVED_VAR(/obj/item/mech_component/chassis, transparent_cabin)
SAVED_VAR(/obj/item/mech_component/chassis, hide_pilot)
SAVED_VAR(/obj/item/mech_component/chassis, hatch_descriptor)
SAVED_VAR(/obj/item/mech_component/chassis, pilot_positions)
SAVED_VAR(/obj/item/mech_component/chassis, min_pilot_size)
SAVED_VAR(/obj/item/mech_component/chassis, max_pilot_size)
SAVED_VAR(/obj/item/mech_component/chassis, climb_time)

SAVED_VAR(/obj/structure/heavy_vehicle_frame, arms)
SAVED_VAR(/obj/structure/heavy_vehicle_frame, legs)
SAVED_VAR(/obj/structure/heavy_vehicle_frame, head)
SAVED_VAR(/obj/structure/heavy_vehicle_frame, body)
SAVED_VAR(/obj/structure/heavy_vehicle_frame, is_wired)
SAVED_VAR(/obj/structure/heavy_vehicle_frame, is_reinforced)
SAVED_VAR(/obj/structure/heavy_vehicle_frame, set_name)

SAVED_VAR(/obj/item/mech_component/sensors, vision_flags)
SAVED_VAR(/obj/item/mech_component/sensors, see_invisible)
SAVED_VAR(/obj/item/mech_component/sensors, camera)
SAVED_VAR(/obj/item/mech_component/sensors, software)
SAVED_VAR(/obj/item/mech_component/sensors, active_sensors)

SAVED_VAR(/obj/item/mech_component/propulsion, move_delay)
SAVED_VAR(/obj/item/mech_component/propulsion, turn_delay)
SAVED_VAR(/obj/item/mech_component/propulsion, motivator)

SAVED_VAR(/obj/item/mech_equipment, owner)
SAVED_VAR(/obj/item/mech_equipment, mech_layer)

SAVED_VAR(/obj/item/mech_equipment/sleeper, sleeper)

SAVED_VAR(/obj/item/mech_equipment/clamp, carrying)