name: Build Release

on:
  push:
    branches:
    - dev

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.8.1


